app = "mailmask"
primary_region = "dfw"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = "suspend"
  auto_start_machines = true

[mounts]
  source = "mailmask_data"
  destination = "/app/data"
